# Generated by Django 2.2.2 on 2019-07-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='bluecredituser',
        #     name='ConfirmPassword',
        #     field=models.CharField(max_length=38, null=True),
        # ),
        # migrations.AddField(
        #     model_name='bluecredituser',
        #     name='Created',
        #     field=models.DateTimeField(auto_now=True),
        # ),
        # migrations.AddField(
        #     model_name='bluecredituser',
        #     name='EmailAddress',
        #     field=models.EmailField(max_length=254, null=True),
        # ),
        # migrations.AddField(
        #     model_name='bluecredituser',
        #     name='FirstName',
        #     field=models.CharField(max_length=38, null=True),
        # ),
        # migrations.AddField(
        #     model_name='bluecredituser',
        #     name='MobileNumber',
        #     field=models.DecimalField(decimal_places=0, max_digits=11, null=True),
        # ),
        # migrations.AddField(
        #     model_name='bluecredituser',
        #     name='Password',
        #     field=models.CharField(max_length=38, null=True),
        # ),
        migrations.AddField(
            model_name='bluecredituser',
            name='Role',
            field=models.CharField(max_length=38, null=True),
        ),
        migrations.AddField(
            model_name='bluecredituser',
            name='Surname',
            field=models.CharField(max_length=38, null=True),
        ),
        migrations.AddField(
            model_name='bluecredituser',
            name='active',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
