# Generated by Django 2.2.2 on 2019-07-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190716_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='bluecredituser',
            name='Createddate',
            field=models.DateTimeField(auto_now=True),
        ),
        # migrations.AddField(
        #     model_name='bluecredituser',
        #     name='EmailAddress',
        #     field=models.EmailField(max_length=254, null=True),
        # ),
        # migrations.AddField(
        #     model_name='bluecredituser',
        #     name='FirstName',
        #     field=models.CharField(max_length=38, null=True),
        # ),
        # migrations.AddField(
        #     model_name='bluecredituser',
        #     name='MobileNumber',
        #     field=models.DecimalField(decimal_places=0, max_digits=11, null=True),
        # ),
    ]
