# Generated by Django 2.2.2 on 2019-07-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='EmailAddress',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='FirstName',
            field=models.CharField(max_length=38, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='MobileNumber',
            field=models.DecimalField(decimal_places=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Password',
            field=models.CharField(max_length=38, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Role',
            field=models.CharField(max_length=38, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Surname',
            field=models.CharField(max_length=38, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ConfirmPassword',
            field=models.CharField(max_length=38, null=True),
        ),
    ]
