# Generated by Django 2.2.2 on 2019-07-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190707_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='bvn_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('bvn', models.IntegerField()),
                ('first_name', models.CharField(max_length=38, null=True)),
                ('last_name', models.CharField(max_length=38, null=True)),
                ('middle_name', models.CharField(max_length=38, null=True)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.IntegerField()),
                ('registration_date', models.DateField()),
                ('enrollment_bank', models.IntegerField()),
                ('enrollment_branch', models.CharField(max_length=38, null=True)),
            ],
        ),
    ]
