# Generated by Django 2.2.2 on 2019-07-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_bvn_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
