# Generated by Django 2.2.2 on 2019-07-17 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Create',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bvn', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HomeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearlyloans', models.CharField(default='240,000', max_length=100)),
                ('minimuminterest', models.CharField(default='15%', max_length=100)),
                ('maxmonths', models.CharField(default='24', max_length=100)),
                ('maxloan', models.CharField(default='1,000,000', max_length=100)),
                ('customerservice', models.CharField(default='24/7', max_length=100)),
                ('bluehostemail', models.CharField(default='info@bluecredit.com', max_length=100)),
                ('phone', models.IntegerField(default=234808080808)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Personaldetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='240,000', max_length=100)),
                ('surname', models.CharField(default='15%', max_length=100)),
                ('middlename', models.CharField(default='24', max_length=100)),
                ('mobilephone', models.CharField(default='1,000,000', max_length=100)),
                ('title', models.CharField(default='Eko Hotels', max_length=100)),
                ('dateofbirth', models.CharField(default='admin@mail.com', max_length=100)),
                ('maritalstatus', models.CharField(default='1 million', max_length=100)),
                ('email', models.CharField(default='24', max_length=100)),
                ('timeataddress', models.CharField(default='1,000,000', max_length=100)),
                ('other', models.CharField(default='Eko Hotels', max_length=100)),
                ('numberofdependents', models.CharField(default='admin@mail.com', max_length=100)),
                ('placeofbirth', models.CharField(default='1 million', max_length=100)),
                ('homeaddress', models.CharField(default='1 million', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bankname', models.CharField(default='Bankname', max_length=100)),
                ('Existing_bank_account_number', models.CharField(default='0000000', max_length=100)),
                ('Highest_level_of_education', models.CharField(default='Degree', max_length=100)),
                ('Employment_status', models.CharField(default='employed', max_length=100)),
                ('Current_employer', models.CharField(default='Mr Wale', max_length=100)),
                ('Employers_address_and_department', models.CharField(default='CEO', max_length=100)),
                ('Landmark_closest_to_address', models.CharField(default='Eko', max_length=100)),
                ('Income', models.CharField(default='1 million', max_length=100)),
                ('Net_monthly_income_with_tax', models.CharField(default='1 million', max_length=100)),
                ('user_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='Createnextofkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nextofkinname', models.CharField(default='240,000', max_length=100)),
                ('nextofkinrelationship', models.CharField(default='15%', max_length=100)),
                ('nextofkinaddress', models.CharField(default='24', max_length=100)),
                ('nextofkinphone', models.CharField(default='1,000,000', max_length=100)),
                ('landmark', models.CharField(default='Eko Hotels', max_length=100)),
                ('nextofkinemail', models.CharField(default='admin@mail.com', max_length=100)),
                ('income', models.CharField(default='1 million', max_length=100)),
                ('user_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Official_email_address', models.CharField(default='email@mail.com', max_length=100)),
                ('Official_pay_day', models.CharField(default='0000000', max_length=100)),
                ('Loan_amount', models.CharField(default='Degree', max_length=100)),
                ('Tenor_agreed', models.CharField(default='employed', max_length=100)),
                ('Number_of_cheques_submitted', models.CharField(default='Mr Wale', max_length=100)),
                ('Account_name', models.CharField(default='CEO', max_length=100)),
                ('NUBAN_account_number', models.CharField(default='Eko', max_length=100)),
                ('Bank_name', models.CharField(default='Zenith', max_length=100)),
                ('Net_monthly_income', models.CharField(default='1 million', max_length=100)),
                ('Amount_requested', models.CharField(default='1 million', max_length=100)),
                ('user_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='backend.user')),
            ],
        ),
    ]
