# Generated by Django 2.2.2 on 2019-06-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearlyloans', models.CharField(default='240,000', max_length=100)),
                ('minimuminterest', models.CharField(default='15%', max_length=100)),
                ('maxmonths', models.CharField(default='24', max_length=100)),
                ('maxloan', models.CharField(default='1,000,000', max_length=100)),
                ('customerservice', models.CharField(default='24/7', max_length=100)),
                ('bluehostemail', models.CharField(default='info@bluecredit.com', max_length=100)),
                ('phone', models.IntegerField(default=234808080808)),
            ],
        ),
    ]
