# Generated by Django 2.2.2 on 2019-07-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='createnextofkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nextofkinname', models.CharField(default='240,000', max_length=100)),
                ('nextofkinrelationship', models.CharField(default='15%', max_length=100)),
                ('nextofkinaddress', models.CharField(default='24', max_length=100)),
                ('nextofkinphone', models.CharField(default='1,000,000', max_length=100)),
                ('landmark', models.CharField(default='Eko Hotels', max_length=100)),
                ('nextofkinemail', models.CharField(default='admin@mail.com', max_length=100)),
                ('income', models.CharField(default='1 million', max_length=100)),
            ],
        ),
    ]
