# Generated by Django 2.2.2 on 2019-07-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_createnextofkin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personaldetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='240,000', max_length=100)),
                ('surname', models.CharField(default='15%', max_length=100)),
                ('middlename', models.CharField(default='24', max_length=100)),
                ('mobilephone', models.CharField(default='1,000,000', max_length=100)),
                ('title', models.CharField(default='Eko Hotels', max_length=100)),
                ('dateofbirth', models.CharField(default='admin@mail.com', max_length=100)),
                ('maritalstatus', models.CharField(default='1 million', max_length=100)),
                ('email', models.CharField(default='24', max_length=100)),
                ('timeataddress', models.CharField(default='1,000,000', max_length=100)),
                ('other', models.CharField(default='Eko Hotels', max_length=100)),
                ('numberofdependents', models.CharField(default='admin@mail.com', max_length=100)),
                ('placeofbirth', models.CharField(default='1 million', max_length=100)),
                ('homeaddress', models.CharField(default='1 million', max_length=100)),
            ],
        ),
    ]
